version: '3.8'

services:
  web:
    image: php:8.2-apache
    container_name: php-web
    volumes:
       - /home/parrot/Documents/www:/var/www/html
    ports:
      - "8080:80"
    depends_on:
      - db
    networks:
      - mynet
    command: bash -c "docker-php-ext-install mysqli && apache2-foreground"

  db:
    image: mysql:8.0
    container_name: mysql-db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: mydb
      MYSQL_USER: user
      MYSQL_PASSWORD: pass
    volumes:
      - db_data:/var/lib/mysql
    networks:
      - mynet

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: phpmyadmin
    restart: always
    environment:
      PMA_HOST: db
      PMA_USER: root
      PMA_PASSWORD: root
    ports:
      - "8081:80"
    depends_on:
      - db
    networks:
      - mynet

volumes:
  db_data:

networks:
  mynet:
